version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - '3300:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  postgresdb:
        image: postgres:latest
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_DB=app
            - POSTGRES_USER=app
            - POSTGRES_PASSWORD=pass
  nodejs:
      build: ./gate-simulator
      image: nodejs:1.0
      ports:
          - '9999:9999'



